apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      # Security context to run as non-root.
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: nginx
        image: reg.mini.dev/mini_pe8ef15af80ele8zow4sunmbtngnhy4u/nginx:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        # Mount the custom nginx.conf over the default configuration.
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        # Mount the custom index.html into the document root.
        - name: index-page
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: nginx-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: index-page
        configMap:
          name: index-page
      - name: nginx-cache
        emptyDir: {}
